### ISSUE TITLE
ListRow with with multiple item rows

### ISSUE THREAD

**Issue by jrocharodrigues** [android/tv-samples#3] opened 2019-09-27 13:56 UTC
Hi, i'm using RowsSupportFragment to have multiple rows on a fragment with presenters.

For one of the rows i want it to be like a verticalgridfragment (multiple rows and columns of items).
The effect i want is the one in row3:

```
|----------------------------|
|    Row 1                   |
|    Item Item ... Item      |
|                            |
|    Row 2                   |
|    Item Item ... Item      |
|                            |
|    Row 3                   |
|    Item Item ... Item      |
|    Item Item ... Item      |
|    Item Item ... Item      |
|    Item Item ... Item      |
-----------------------------
```

I've seted the num of rows of the List row presenter to 6, it presents multiple rows, but when i scroll down the fragment does not scroll to show the rows that are not visible, like it does when i scroll to a different ListRow.

Is there anyway to do it? 

Thanks in advance

**Comment by owahltinez** [comment] 2019-10-10 14:56
Hey Jose, I'm not quite sure what you mean. If the issue is that `Row 3` is so large that it overflows on the bottom when in focus, then you can call `RowPresenter.setFacet`[1] to center it on the screen but likely that won't be enough since 6 rows will be too large to fit on a screen.

If what you are trying to do is nested vertical scrolling... I would recommend not to do that from a UX perspective. In theory it should be possible if you set the height of `Row 3` to something smaller than its actual height.

[1] https://developer.android.com/reference/android/support/v17/leanback/widget/Presenter.html#setFacet(java.lang.Class%3C?%3E,%20java.lang.Object)

**Comment by jrocharodrigues** [comment] 2019-10-10 15:47
Hi @owahltinez , thanks for your answer .

I'll make some tests using the setFacet method you suggested.

What i'm trying to do is to have the same effect of having 6  or more different rows, of the same object type, but without the complexity of creating multiple adapters and having the navigation like a grid.

**Comment by esillen** [comment] 2019-11-20 15:47
I want to do the same thing!

**Comment by IanGClifton** [comment] 2019-12-27 19:49
It sounds like this is more of a general implementation question than a question with these specific examples. StackOverflow (http://stackoverflow.com/questions/tagged/android-tv) is a better forum for those types of questions because you'll have a much larger audience to offer help, so I'm going to close this out.

**Closed by IanGClifton** 2019-12-27 19:49 UTC
